### ISSUE TITLE
Move Dependencies

### ISSUE THREAD

**Issue by mehrdadrafiee** [nazarimohamad/sublock#4]
I think most of the dependencies in `client/package.json` can be moved to `devDependencies` section. I don't know the difference yet, but please let me know if figure out what the difference is :)

**Comment by nazarimohamad** [comment]
Using `create-react-app` creat a port for itself (`localhost:3000`) and also when creating a server, another port and `package.json` will be created. This folder structure is one of the most used structures, separating front-end and back-end into different directories in MERN-stack. And to be honest, I barely see one structure.
